function cellInfo = setupBuses(varargin) 
% MYBUSES returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'eepromConfig_t', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'version',                        1, 'uint8',  -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'mpuTempMin',                     1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'mpuTempMax',                     1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'accelBiasPolynomial',        [3 4], 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'accelScaleFactorPolynomial', [3 4], 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'gyroBiasPolynomial',         [3 4], 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'magBias',                        6, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'accelCutoff',                    1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'kpAcc',                          1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'kpMag',                          1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'earthAccel100HzHPtau',           1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'posEstA',                        1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'posEstB',                        1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'hEstA',                          1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'hEstB',                          1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'dlpfSetting',                    1, 'uint8',  -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'sensorOrientation',              1, 'uint8',  -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'attTrim',                        2, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rollAndPitchRateScaling',        1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'yawRateScaling',                 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'attitudeScaling',                1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'nDotEdotScaling',                1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'hDotScaling',                    1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'receiverType',                   1, 'uint8',  -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'slaveSpektrum',                  1, 'uint8',  -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rcMap',                          8, 'uint8',  -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'escPwmRate',                     1, 'uint16', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'servoPwmRate',                   1, 'uint16', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'midCommand',                     1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'minCheck',                       1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'maxCheck',                       1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'minThrottle',                    1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'maxThrottle',                    1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'mixerConfiguration',             1, 'uint8',  -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'yawDirection',                   1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'triYawServoPwmRate',             1, 'uint16', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'triYawServoMin',                 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'triYawServoMid',                 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'triYawServoMax',                 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'triCopterYawCmd500HzLowPassTau', 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'freeMixMotors',                  1, 'uint8',  -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'freeMix',                    [8 4], 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rateP',                          3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rateI',                          3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rateD',                          3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rateLimit',                      3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'attitudeP',                      3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'attitudeI',                      3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'attitudeD',                      3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'attitudeLimit',                  3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'velocityP',                      3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'velocityI',                      3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'velocityD',                      3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'velocityLimit',                  3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'positionP',                      3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'positionI',                      3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'positionD',                      3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'positionLimit',                  3, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rollAttAltCompensationGain',     1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'rollAttAltCompensationLimit',    1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'pitchAttAltCompensationGain',    1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'pitchAttAltCompensationLimit',   1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'batteryCells',                   1, 'uint8',  -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'voltageMonitorScale',            1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'voltageMonitorBias',             1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'batteryLow',                     1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'batteryVeryLow',                 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'batteryMaxLow',                  1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'armCount',                       1, 'uint8',  -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'disarmCount',                    1, 'uint8',  -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'activeTelemetry',                1, 'uint16', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'mavlinkEnabled',                 1, 'uint8',  -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'useGPS',                         1, 'uint8',  -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'verticalVelocityHoldOnly',       1, 'uint8',  -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'externalHMC5883',                1, 'uint8',  -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'externalMS5611',                 1, 'uint8',  -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CRCFlags',                       1, 'uint8',  -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CRCAtEnd',                       1, 'uint32', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
